export const Login_Middle_Point = "/api/user";
export const User_Middle_Point = "/api/user";
export const Product_Middle_Point ="/api/products";
export const Stock_Middle_Point ="/api/stock";
export const Order_Middle_Point ="/api/orders";
export const Category_Middle_Point ="/api/category";
export const Tag_Middle_Point ="/api/tag";
export const Warehouse_Middle_Point ="/api/warehouse";
export const Deliver_Middle_Point ="/api/orders";
