import { useState } from "react";
import Navbar from "../../Navbar/Navbar";
import LeftSideBar from "../../LeftSideBar/LeftSideBar";

const ReportRegistrationForm = () => {
  const [formData, setFormData] = useState({
    reportTitle: "",
    reportType: "",
    dateGenerated: "",
    generatedBy: "",
    status: "",
    description: "",
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    console.log("Report Registered:", formData);
    alert("Report registered successfully!");
    setFormData({
      reportTitle: "",
      reportType: "",
      dateGenerated: "",
      generatedBy: "",
      status: "",
      description: "",
    });
  };

  return (
    <>
      <Navbar />
      <div className="flex flex-col lg:flex-row">
        <LeftSideBar />
        <div className="flex flex-col items-center lg:ml-10 w-full lg:w-[1000px] h-screen">
          <form
            onSubmit={handleSubmit}
            className="bg-white mt-5 shadow-lg rounded-lg p-6 w-full lg:w-[800px] border border-gray-300"
          >
            <h2 className="text-2xl font-bold mb-6 text-center text-gray-700">
              Report Registration
            </h2>

            <div className="flex flex-col lg:flex-row justify-between">
              <div className="w-full lg:w-[350px]">
                <label
                  htmlFor="reportTitle"
                  className="block text-sm font-medium text-gray-600"
                >
                  Report Title <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="reportTitle"
                  id="reportTitle"
                  value={formData.reportTitle}
                  onChange={handleChange}
                  className="w-full mt-2 px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter report title"
                  required
                />
              </div>
              <div className="w-full lg:w-[350px]">
                <label
                  htmlFor="reportType"
                  className="block text-sm font-medium text-gray-600"
                >
                  Report Type <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="reportType"
                  id="reportType"
                  value={formData.reportType}
                  onChange={handleChange}
                  className="w-full mt-2 px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter report type"
                  required
                />
              </div>
            </div>

            <div className="flex flex-col lg:flex-row justify-between mt-5">
              <div className="w-full lg:w-[350px]">
                <label
                  htmlFor="dateGenerated"
                  className="block text-sm font-medium text-gray-600"
                >
                  Date Generated <span className="text-red-500">*</span>
                </label>
                <input
                  type="date"
                  name="dateGenerated"
                  id="dateGenerated"
                  value={formData.dateGenerated}
                  onChange={handleChange}
                  className="w-full mt-2 px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  required
                />
              </div>
              <div className="w-full lg:w-[350px]">
                <label
                  htmlFor="generatedBy"
                  className="block text-sm font-medium text-gray-600"
                >
                  Generated By <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="generatedBy"
                  id="generatedBy"
                  value={formData.generatedBy}
                  onChange={handleChange}
                  className="w-full mt-2 px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter generated by"
                  required
                />
              </div>
            </div>

            <div className="flex flex-col lg:flex-row justify-between mt-5">
              <div className="w-full lg:w-[350px]">
                <label
                  htmlFor="status"
                  className="block text-sm font-medium text-gray-600"
                >
                  Status <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="status"
                  id="status"
                  value={formData.status}
                  onChange={handleChange}
                  className="w-full mt-2 px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter report status"
                  required
                />
              </div>
              <div className="w-full lg:w-[350px]">
                <label
                  htmlFor="description"
                  className="block text-sm font-medium text-gray-600"
                >
                  Description <span className="text-red-500">*</span>
                </label>
                <textarea
                  name="description"
                  id="description"
                  value={formData.description}
                  onChange={handleChange}
                  className="w-full mt-2 px-4 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Enter description"
                  required
                />
              </div>
            </div>

            <div className="flex justify-end mt-6">
              <button
                type="submit"
                className="px-6 py-2 bg-[#F0FFF8] border rounded-md hover:bg-[#F0FFF8] transition duration-200
"
              >
                Register Report
              </button>
            </div>
          </form>
        </div>
      </div>
    </>
  );
};

export default ReportRegistrationForm;
